### ISSUE TITLE
Implement Listen View

### ISSUE THREAD

**Issue by kmahelona** [TeHikuMedia/corpora-expo#5]
## Listen View ##

This view allows people to listen to other recordings and vote on them (good/thumbs up or bad/thumbs down).

The view should,
1. Get a recording from the local storage or the API when the storage is empty
2. Allow the user to play the recording
    1. When playback is complete, enable the vote buttons
3. The user hits "thumbs up" or "thumbs down" to vote on the recording
    1. Visually indicate to the user that their vote is being "saved"
4. We store the users vote locally and queue it for upload.
5. Fetch next recording and repeat 1-5.

### API ###
To get a single recording for review, `https://dev.koreromaori.com/api/listen/?sort_by=random`

To get a list of recording objects, e.g. to prefetch recordings for offline recording, `https://dev.koreromaori.com/api/listen/`.

Note there's some trickery with the recording file url e.g. `https://dev.koreromaori.com/recording-file/2411/` to protect data, so you'll have to call that url with `?format=json` and get the redirect for a signed url to the object in an S3 object. This is implemented [here](https://github.com/TeHikuMedia/corpora-expo/blob/master/utils/SentenceListenView.js#L173).

**Comment by allan-walker** [comment]
From Keoni:

> One bit of feedback. Can you reset the play button so after the audio finished playing the user can play it again (similar behaviour on the record view) also disable the vote buttons until the audio is completely played. that prevents someone from voting without actually listening to the entire recordings.

**Comment by allan-walker** [comment]
We also need to visually indicate the voting has happened

**Comment by kmahelona** [comment]
Implemented in https://github.com/TeHikuMedia/corpora-expo/releases/tag/v1.0.2
